# Generated by Django 5.1.5 on 2025-02-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
    ]
