# Generated by Django 5.1.5 on 2025-02-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='balcony',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
