# Generated by Django 5.1.5 on 2025-02-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_room_balcony_room_bathrooms_room_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
    ]
