# Generated by Django 5.1.5 on 2025-02-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.PositiveIntegerField(choices=[(1, '1 People'), (2, '2 People'), (3, '3 People'), (4, '4 People'), (5, '5 People')]),
        ),
    ]
