# Generated by Django 5.1.5 on 2025-02-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_booking_guests'),
    ]

    operations = [
        migrations.CreateModel(
            name='teg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=30)),
            ],
        ),
    ]
