# Generated by Django 5.1.5 on 2025-02-09 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_booking_guests_booking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teg',
            name='icon',
        ),
        migrations.AddField(
            model_name='teg',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tegs', to='blog.room'),
            preserve_default=False,
        ),
    ]
