# Generated by Django 5.1.5 on 2025-02-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_teg_icon_teg_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='teg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
