# Generated by Django 5.1.5 on 2025-02-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_teg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teg',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
