# Generated by Django 5.1.5 on 2025-02-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='position',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
