# Generated by Django 5.1.5 on 2025-02-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image',
            new_name='f_image',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='image2',
            new_name='f_image2',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='f_name',
        ),
        migrations.AddField(
            model_name='service',
            name='m_image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='m_image2',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='m_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='r_image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='r_image2',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='r_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='s_image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='s_image2',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='s_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
